param(
	[string]$Flatc = $env:UPI_FLATC,
	[switch]$AllowDifferentFlatcVersion
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent $ScriptDir
$NodeShellDir = Join-Path $RepoRoot "node-shell"
$ProtocolDir = Join-Path $RepoRoot "node-shell\packages\protocol"
$CppOut = Join-Path $ProtocolDir "generated\cpp"
$TsOut = Join-Path $ProtocolDir "generated\ts"
$JsOut = Join-Path $ProtocolDir "generated\js"
$GeneratedOut = Join-Path $ProtocolDir "generated"
$RequiredFlatcVersion = "24.3.25"

function ConvertTo-LfLineEndings {
	param(
		[string]$Root
	)

	$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
	$GeneratedFiles = @(Get-ChildItem -Path $Root -Recurse -File)
	foreach ($File in $GeneratedFiles) {
		$Bytes = [System.IO.File]::ReadAllBytes($File.FullName)
		$Text = $Utf8NoBom.GetString($Bytes)
		$Normalized = $Text.Replace("`r`n", "`n").Replace("`r", "`n")
		if ($Normalized -ne $Text) {
			[System.IO.File]::WriteAllText($File.FullName, $Normalized, $Utf8NoBom)
		}
	}
}

function Set-GeneratedTypescriptBarrel {
	param(
		[string]$BarrelPath
	)

	# flatc 24.3.25 overwrites the namespace entrypoint per schema; keep our barrel complete and reproducible.
	$Exports = @(
		"export { BackendInfoResponse } from './v1/backend-info-response.js';",
		"export { IoStoreAnalysisResponse } from './v1/io-store-analysis-response.js';",
		"export { IoStoreChunkEntry } from './v1/io-store-chunk-entry.js';",
		"export { IoStoreCompressedBlockEntry } from './v1/io-store-compressed-block-entry.js';",
		"export { IoStoreOverview } from './v1/io-store-overview.js';",
		"export { IoStorePackageEntry } from './v1/io-store-package-entry.js';",
		"export { IoStorePartition } from './v1/io-store-partition.js';",
		"export { Issue } from './v1/issue.js';",
		"export { IssueSeverity } from './v1/issue-severity.js';",
		"export { PakAnalysisResponse } from './v1/pak-analysis-response.js';",
		"export { PakCompressedBlockEntry } from './v1/pak-compressed-block-entry.js';",
		"export { PakOverview } from './v1/pak-overview.js';",
		"export { PakPackageEntry } from './v1/pak-package-entry.js';",
		"export { ResponseStatus } from './v1/response-status.js';"
	)
	$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
	$Content = @(
		"// automatically generated by the FlatBuffers compiler, do not modify",
		"",
		"/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */",
		""
	) + $Exports
	[System.IO.File]::WriteAllText($BarrelPath, (($Content -join "`n") + "`n"), $Utf8NoBom)
}

if ([string]::IsNullOrWhiteSpace($Flatc)) {
	$Command = Get-Command flatc -ErrorAction SilentlyContinue
	if ($Command) {
		$Flatc = $Command.Source
	}
}

if ([string]::IsNullOrWhiteSpace($Flatc) -or !(Test-Path -LiteralPath $Flatc)) {
	throw "flatc not found. Install the FlatBuffers compiler or set UPI_FLATC to flatc.exe."
}

$FlatcVersionOutput = (& $Flatc --version)
if ($LASTEXITCODE -ne 0) {
	throw "flatc --version failed for $Flatc."
}
$FlatcVersion = ($FlatcVersionOutput -join "`n").Trim() -replace '^flatc version\s+', ''
if (($FlatcVersion -ne $RequiredFlatcVersion) -and !$AllowDifferentFlatcVersion) {
	throw "flatc version $FlatcVersion is not supported. Expected $RequiredFlatcVersion. Use -AllowDifferentFlatcVersion to override intentionally."
}

$Tsc = Join-Path $NodeShellDir "node_modules\.bin\tsc.cmd"
if (!(Test-Path -LiteralPath $Tsc)) {
	throw "TypeScript compiler not found at $Tsc. Run npm install from node-shell before generating protocol bindings."
}

foreach ($OutDir in @($CppOut, $TsOut, $JsOut)) {
	if (Test-Path -LiteralPath $OutDir) {
		Remove-Item -LiteralPath $OutDir -Recurse -Force
	}
	New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
}

$Schemas = @(
	"upi_backend_info.fbs",
	"upi_pak_analysis.fbs",
	"upi_iostore_analysis.fbs"
)

$SchemaPaths = foreach ($Schema in $Schemas) {
	Join-Path $ProtocolDir $Schema
}

$CommonSchemaPath = Join-Path $ProtocolDir "upi_common.fbs"
$AllSchemaPaths = @($CommonSchemaPath) + $SchemaPaths

& $Flatc --warnings-as-errors --cpp --filename-suffix "_generated" -o $CppOut -I $ProtocolDir @AllSchemaPaths
if ($LASTEXITCODE -ne 0) {
	throw "flatc C++ generation failed."
}

& $Flatc --warnings-as-errors --ts -o $TsOut -I $ProtocolDir @AllSchemaPaths
if ($LASTEXITCODE -ne 0) {
	throw "flatc TypeScript generation failed."
}

Set-GeneratedTypescriptBarrel -BarrelPath (Join-Path $TsOut "upi\v1.ts")

$TsFiles = @(Get-ChildItem -Path $TsOut -Recurse -Filter "*.ts" | Select-Object -ExpandProperty FullName)
if (!$TsFiles -or $TsFiles.Count -eq 0) {
	throw "flatc TypeScript generation produced no .ts files in $TsOut."
}

$TscArgs = @(
	"--target", "ES2020",
	"--module", "commonjs",
	"--moduleResolution", "node",
	"--rootDir", $TsOut,
	"--outDir", $JsOut,
	"--skipLibCheck",
	"--noEmitOnError"
) + $TsFiles

& $Tsc @TscArgs
if ($LASTEXITCODE -ne 0) {
	throw "TypeScript compilation failed for generated protocol bindings."
}

ConvertTo-LfLineEndings -Root $GeneratedOut

Write-Output "[OK] Generated FlatBuffers bindings in $ProtocolDir\generated"
